//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMaster
    {
        public int ID { get; set; }
        public string CITY { get; set; }
        public bool IS_ACTIVE { get; set; }
        public bool IS_DELETE { get; set; }
        public System.DateTime DATE { get; set; }
        public System.TimeSpan TIME { get; set; }
    }
}
